variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  BUCKET_NAME: $BUCKET_NAME
  CLOUDFRONT_DIST_ID: $CLOUDFRONT_DIST_ID
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image: registry.gitlab.com/pages/hugo:0.55.6
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

deploy:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install awscli
  script:
    - aws configure set preview.cloudfront true
    - aws s3 sync ./public s3://$BUCKET_NAME --delete;
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID  --paths "/*";
  only:
  - master
