# Site settings
title: Matteo Madeddu
motto: Mac OS lover, Docker fan, Go explorer, Python geek, Blogger, Juggler.
language: "en"
email:
  address: "matteo.madeddu@gmail.com"
  text: "matteo.madeddu [at] gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  "Mac OS lover, Docker fan, Go explorer, Python geek, Blogger, Juggler."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://madeddu.xyz" # the base hostname & protocol for your site
twitter_username: made2591
github_username:  made2591

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 6
paginate_path: /posts/page-:num
permalink: /posts/:title/

# disqus comment
disqus:
  shortname: "madeddu-xyz" #your disqus comment short name

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
disqus-id: madeddu-xyz

enable-share: true
github: 'https://github.com/made2591/'
# stack-overflow: 'https://stackoverflow.com/'
twitter: 'https://twitter.com/made2591'
linkedin: 'https://linkedin.com/in/mmadeddu'
# youtube: ''
facebook: 'https://www.facebook.com/matteo.madeddu'

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jemoji']

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
