name: Matteo Madeddu
on:
  push:
    branches:
      - dev

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/docker/cli@master
        with:
          args: pull registry.gitlab.com/pages/hugo:0.55.6

  build:
    needs: checkout
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/docker/cli@master
        with:
          args: run registry.gitlab.com/pages/hugo:0.55.6 hugo

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/aws/cli@master
        with:
          args: aws s3 ls
